### PR TITLE
Upgrading theia version to 0.3.13

### PR DESCRIPTION
**Pull request by sunix**
fix compilation errors
https://github.com/eclipse/che/issues/10810

### CODE REVIEW

**Comment by AndrienkoAleksandr** [comment]
What about yarn.lock?

**Comment by sunix** [comment]
@AndrienkoAleksandr to me yarn.lock is a way to hide problems ...

**Comment by sunix** [comment]
@mmorhun what should I check ? README is missing user stories that tell how this extension is supposed to work. At the moment, I have checked that this is fixing the compilation errors we have https://github.com/eclipse/che/issues/10810

**Comment by mmorhun** [comment]
@sunix please add into description what exactly this PR does (like fix compilation issue). Also link to original issue (if any) are usually appreciated.

**Pull request merged**
